function CDF_warning(warn)
CDF_warn=figure(...
   'Visible','on', ...
   'Units','normalized',...
   'Name','CDF_warn', ...
   'Color',[.3 .3 .3],...
   'Tag','CDF_warn',...
   'NumberTitle','off');


    wHndl=uicontrol( ...
	'Style','text', ...
        'Units','normalized', ...
        'Max',10, ...
        'BackgroundColor',[.9 .9 .9], ...
        'Position',[.05,.25,.9,.7], ...
        'FontSize',10, ...
        'FontUnits','normalized',...
        'HorizontalAlignment','left', ...
        'String',warn);

   closeStr=['delete(gcf);'];
   uicontrol('Style','push','Units','normalized', ...
          'FontUnits','normalized',...
          'Position',[.79,.05,.14,.08], ...
          'Callback',closeStr, ...
          'BackgroundColor',[.5,0.5,0.5], ...
          'String','OK');
