function HAZ_datasave(X)

dsavefig=figure( ...
   'Visible','on', ...
   'Name','Data Saving', ...
   'Units','Normalized',...
   'Tag','HAZ_DATASAVE',...
   'NumberTitle','off');

uicontrol( ...
        'Style','text', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.8,.6,.1], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'FontSize',0.5,...
        'String','Choose variables to save:');

Xsave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.7,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_X',...
        'String',' Random variable - X');

Xsave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.6,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_d',...
        'String',' Censoring indicator - d');

Ksave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.5,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_K',...
        'String',' Kernel - K');

hsave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.4,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_h',...
        'String',' Bandwidth - h');

xsave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.3,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_xx',...
        'String',' Points of x-axis  - xx');

festsave=uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.2,.6,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_f',...
        'String',' Kernel estimate in points xx - haf_est');

sdata0='mf=findobj(''Tag'',''HAZ_MAIN'');udata=get(mf,''UserData'');X=udata.X;d=udata.d;K=udata.K;h=udata.h;xx=udata.xx;F_est=udata.F_est;';
sdata1='varlist=[];v_hand=findobj(''Tag'',''HAZ_SAVE_X'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''X''''''];end;';
sdata2='v_hand=findobj(''Tag'',''HAZ_SAVE_d'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''d''''''];end;';
sdata3='v_hand=findobj(''Tag'',''HAZ_SAVE_K'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''K''''''];end;';
sdata4='v_hand=findobj(''Tag'',''HAZ_SAVE_h'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''h''''''];end;';
sdata5='v_hand=findobj(''Tag'',''HAZ_SAVE_xx'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''xx''''''];end;';
sdata6='v_hand=findobj(''Tag'',''HAZ_SAVE_f'');v_use=get(v_hand,''Value'');if v_use, varlist=[varlist,'',''''F_est''''''];end;';
sdata7='if length(varlist)>0, varlist(1)=[]; savecmd=[''uisave({'',varlist,''},''''HAZ_data'''');''];eval(savecmd);close(gcf); end;';
datatsave=uicontrol( ...
        'Style','Push', ...
        'Units','normalized', ...
        'FontUnits','normalized',...
        'Position',[.2,.2,.3,.075], ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ForegroundColor',[0 0 0], ...
        'Tag','HAZ_SAVE_DATA',...
        'String','Save selected variables', ...
        'Callback',[sdata0,sdata1,sdata2,sdata3,sdata4,sdata5,sdata6,sdata7]);



